// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control_data.proto

package com.letv.accountLogin.protobuf;

public final class ControlDataProto {
  private ControlDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ParcelOrBuilder extends com.google.protobuf.MessageOrBuilder {
    
    // required .com.letv.accountLogin.protobuf.Parcel.DataType type = 1;
    boolean hasType();
    com.letv.accountLogin.protobuf.ControlDataProto.Parcel.DataType getType();
    
    // optional string from = 2;
    boolean hasFrom();
    String getFrom();
    
    // optional string to = 3;
    boolean hasTo();
    String getTo();
    
    // optional int32 keyCode = 4;
    boolean hasKeyCode();
    int getKeyCode();
    
    // optional string msgInfo = 5;
    boolean hasMsgInfo();
    String getMsgInfo();
    
    // optional string token = 6;
    boolean hasToken();
    String getToken();
    
    // optional string signature = 7;
    boolean hasSignature();
    String getSignature();
    
    // optional string errorCode = 8;
    boolean hasErrorCode();
    String getErrorCode();
  }
  public static final class Parcel extends
      com.google.protobuf.GeneratedMessage
      implements ParcelOrBuilder {
    // Use Parcel.newBuilder() to construct.
    private Parcel(Builder builder) {
      super(builder);
    }
    private Parcel(boolean noInit) {}
    
    private static final Parcel defaultInstance;
    public static Parcel getDefaultInstance() {
      return defaultInstance;
    }
    
    public Parcel getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.letv.accountLogin.protobuf.ControlDataProto.internal_static_com_letv_accountLogin_protobuf_Parcel_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.letv.accountLogin.protobuf.ControlDataProto.internal_static_com_letv_accountLogin_protobuf_Parcel_fieldAccessorTable;
    }
    
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      PING(0, 0),
      ONLINE(1, 1),
      ONLINE_ACK(2, 2),
      OFFLINE(3, 3),
      OFFLINE_ACK(4, 4),
      KEY_STRIKE(5, 5),
      MSG_INFO(6, 6),
      MSG_INFO_ACK(7, 7),
      ;
      
      public static final int PING_VALUE = 0;
      public static final int ONLINE_VALUE = 1;
      public static final int ONLINE_ACK_VALUE = 2;
      public static final int OFFLINE_VALUE = 3;
      public static final int OFFLINE_ACK_VALUE = 4;
      public static final int KEY_STRIKE_VALUE = 5;
      public static final int MSG_INFO_VALUE = 6;
      public static final int MSG_INFO_ACK_VALUE = 7;
      
      
      public final int getNumber() { return value; }
      
      public static DataType valueOf(int value) {
        switch (value) {
          case 0: return PING;
          case 1: return ONLINE;
          case 2: return ONLINE_ACK;
          case 3: return OFFLINE;
          case 4: return OFFLINE_ACK;
          case 5: return KEY_STRIKE;
          case 6: return MSG_INFO;
          case 7: return MSG_INFO_ACK;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.letv.accountLogin.protobuf.ControlDataProto.Parcel.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final DataType[] VALUES = {
        PING, ONLINE, ONLINE_ACK, OFFLINE, OFFLINE_ACK, KEY_STRIKE, MSG_INFO, MSG_INFO_ACK, 
      };
      
      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private DataType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:com.letv.accountLogin.protobuf.Parcel.DataType)
    }
    
    private int bitField0_;
    // required .com.letv.accountLogin.protobuf.Parcel.DataType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.letv.accountLogin.protobuf.ControlDataProto.Parcel.DataType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.letv.accountLogin.protobuf.ControlDataProto.Parcel.DataType getType() {
      return type_;
    }
    
    // optional string from = 2;
    public static final int FROM_FIELD_NUMBER = 2;
    private java.lang.Object from_;
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getFrom() {
      java.lang.Object ref = from_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          from_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFromBytes() {
      java.lang.Object ref = from_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string to = 3;
    public static final int TO_FIELD_NUMBER = 3;
    private java.lang.Object to_;
    public boolean hasTo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          to_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 keyCode = 4;
    public static final int KEYCODE_FIELD_NUMBER = 4;
    private int keyCode_;
    public boolean hasKeyCode() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getKeyCode() {
      return keyCode_;
    }
    
    // optional string msgInfo = 5;
    public static final int MSGINFO_FIELD_NUMBER = 5;
    private java.lang.Object msgInfo_;
    public boolean hasMsgInfo() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getMsgInfo() {
      java.lang.Object ref = msgInfo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          msgInfo_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMsgInfoBytes() {
      java.lang.Object ref = msgInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        msgInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string token = 6;
    public static final int TOKEN_FIELD_NUMBER = 6;
    private java.lang.Object token_;
    public boolean hasToken() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          token_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string signature = 7;
    public static final int SIGNATURE_FIELD_NUMBER = 7;
    private java.lang.Object signature_;
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getSignature() {
      java.lang.Object ref = signature_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          signature_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSignatureBytes() {
      java.lang.Object ref = signature_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        signature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string errorCode = 8;
    public static final int ERRORCODE_FIELD_NUMBER = 8;
    private java.lang.Object errorCode_;
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getErrorCode() {
      java.lang.Object ref = errorCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          errorCode_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getErrorCodeBytes() {
      java.lang.Object ref = errorCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        errorCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      type_ = com.letv.accountLogin.protobuf.ControlDataProto.Parcel.DataType.PING;
      from_ = "";
      to_ = "";
      keyCode_ = 0;
      msgInfo_ = "";
      token_ = "";
      signature_ = "";
      errorCode_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFromBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getToBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, keyCode_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getMsgInfoBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getTokenBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getSignatureBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getErrorCodeBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFromBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getToBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, keyCode_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getMsgInfoBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getTokenBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getSignatureBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getErrorCodeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.letv.accountLogin.protobuf.ControlDataProto.Parcel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.letv.accountLogin.protobuf.ControlDataProto.Parcel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.letv.accountLogin.protobuf.ControlDataProto.Parcel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.letv.accountLogin.protobuf.ControlDataProto.Parcel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.letv.accountLogin.protobuf.ControlDataProto.Parcel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.letv.accountLogin.protobuf.ControlDataProto.Parcel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.letv.accountLogin.protobuf.ControlDataProto.Parcel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.letv.accountLogin.protobuf.ControlDataProto.Parcel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.letv.accountLogin.protobuf.ControlDataProto.Parcel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.letv.accountLogin.protobuf.ControlDataProto.Parcel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.letv.accountLogin.protobuf.ControlDataProto.Parcel prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.letv.accountLogin.protobuf.ControlDataProto.ParcelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.letv.accountLogin.protobuf.ControlDataProto.internal_static_com_letv_accountLogin_protobuf_Parcel_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.letv.accountLogin.protobuf.ControlDataProto.internal_static_com_letv_accountLogin_protobuf_Parcel_fieldAccessorTable;
      }
      
      // Construct using com.letv.accountLogin.protobuf.ControlDataProto.Parcel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = com.letv.accountLogin.protobuf.ControlDataProto.Parcel.DataType.PING;
        bitField0_ = (bitField0_ & ~0x00000001);
        from_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        to_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        keyCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        msgInfo_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        signature_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        errorCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.letv.accountLogin.protobuf.ControlDataProto.Parcel.getDescriptor();
      }
      
      public com.letv.accountLogin.protobuf.ControlDataProto.Parcel getDefaultInstanceForType() {
        return com.letv.accountLogin.protobuf.ControlDataProto.Parcel.getDefaultInstance();
      }
      
      public com.letv.accountLogin.protobuf.ControlDataProto.Parcel build() {
        com.letv.accountLogin.protobuf.ControlDataProto.Parcel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.letv.accountLogin.protobuf.ControlDataProto.Parcel buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.letv.accountLogin.protobuf.ControlDataProto.Parcel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.letv.accountLogin.protobuf.ControlDataProto.Parcel buildPartial() {
        com.letv.accountLogin.protobuf.ControlDataProto.Parcel result = new com.letv.accountLogin.protobuf.ControlDataProto.Parcel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.from_ = from_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.to_ = to_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.keyCode_ = keyCode_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.msgInfo_ = msgInfo_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.token_ = token_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.signature_ = signature_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.errorCode_ = errorCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.letv.accountLogin.protobuf.ControlDataProto.Parcel) {
          return mergeFrom((com.letv.accountLogin.protobuf.ControlDataProto.Parcel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.letv.accountLogin.protobuf.ControlDataProto.Parcel other) {
        if (other == com.letv.accountLogin.protobuf.ControlDataProto.Parcel.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasFrom()) {
          setFrom(other.getFrom());
        }
        if (other.hasTo()) {
          setTo(other.getTo());
        }
        if (other.hasKeyCode()) {
          setKeyCode(other.getKeyCode());
        }
        if (other.hasMsgInfo()) {
          setMsgInfo(other.getMsgInfo());
        }
        if (other.hasToken()) {
          setToken(other.getToken());
        }
        if (other.hasSignature()) {
          setSignature(other.getSignature());
        }
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.letv.accountLogin.protobuf.ControlDataProto.Parcel.DataType value = com.letv.accountLogin.protobuf.ControlDataProto.Parcel.DataType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              from_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              to_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              keyCode_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              msgInfo_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              token_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              signature_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              errorCode_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .com.letv.accountLogin.protobuf.Parcel.DataType type = 1;
      private com.letv.accountLogin.protobuf.ControlDataProto.Parcel.DataType type_ = com.letv.accountLogin.protobuf.ControlDataProto.Parcel.DataType.PING;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.letv.accountLogin.protobuf.ControlDataProto.Parcel.DataType getType() {
        return type_;
      }
      public Builder setType(com.letv.accountLogin.protobuf.ControlDataProto.Parcel.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.letv.accountLogin.protobuf.ControlDataProto.Parcel.DataType.PING;
        onChanged();
        return this;
      }
      
      // optional string from = 2;
      private java.lang.Object from_ = "";
      public boolean hasFrom() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getFrom() {
        java.lang.Object ref = from_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          from_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFrom(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        from_ = value;
        onChanged();
        return this;
      }
      public Builder clearFrom() {
        bitField0_ = (bitField0_ & ~0x00000002);
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }
      void setFrom(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        from_ = value;
        onChanged();
      }
      
      // optional string to = 3;
      private java.lang.Object to_ = "";
      public boolean hasTo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTo(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        to_ = value;
        onChanged();
        return this;
      }
      public Builder clearTo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      void setTo(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        to_ = value;
        onChanged();
      }
      
      // optional int32 keyCode = 4;
      private int keyCode_ ;
      public boolean hasKeyCode() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getKeyCode() {
        return keyCode_;
      }
      public Builder setKeyCode(int value) {
        bitField0_ |= 0x00000008;
        keyCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearKeyCode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        keyCode_ = 0;
        onChanged();
        return this;
      }
      
      // optional string msgInfo = 5;
      private java.lang.Object msgInfo_ = "";
      public boolean hasMsgInfo() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getMsgInfo() {
        java.lang.Object ref = msgInfo_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          msgInfo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMsgInfo(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msgInfo_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsgInfo() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msgInfo_ = getDefaultInstance().getMsgInfo();
        onChanged();
        return this;
      }
      void setMsgInfo(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        msgInfo_ = value;
        onChanged();
      }
      
      // optional string token = 6;
      private java.lang.Object token_ = "";
      public boolean hasToken() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setToken(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        token_ = value;
        onChanged();
        return this;
      }
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000020);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      void setToken(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        token_ = value;
        onChanged();
      }
      
      // optional string signature = 7;
      private java.lang.Object signature_ = "";
      public boolean hasSignature() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getSignature() {
        java.lang.Object ref = signature_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          signature_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSignature(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        signature_ = value;
        onChanged();
        return this;
      }
      public Builder clearSignature() {
        bitField0_ = (bitField0_ & ~0x00000040);
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      void setSignature(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        signature_ = value;
        onChanged();
      }
      
      // optional string errorCode = 8;
      private java.lang.Object errorCode_ = "";
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getErrorCode() {
        java.lang.Object ref = errorCode_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          errorCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setErrorCode(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        errorCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000080);
        errorCode_ = getDefaultInstance().getErrorCode();
        onChanged();
        return this;
      }
      void setErrorCode(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        errorCode_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.letv.accountLogin.protobuf.Parcel)
    }
    
    static {
      defaultInstance = new Parcel(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.letv.accountLogin.protobuf.Parcel)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_letv_accountLogin_protobuf_Parcel_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_letv_accountLogin_protobuf_Parcel_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022control_data.proto\022\036com.letv.smartCont" +
      "rol.protobuf\"\270\002\n\006Parcel\022=\n\004type\030\001 \002(\0162/." +
      "com.letv.accountLogin.protobuf.Parcel.Da" +
      "taType\022\014\n\004from\030\002 \001(\t\022\n\n\002to\030\003 \001(\t\022\017\n\007keyC" +
      "ode\030\004 \001(\005\022\017\n\007msgInfo\030\005 \001(\t\022\r\n\005token\030\006 \001(" +
      "\t\022\021\n\tsignature\030\007 \001(\t\022\021\n\terrorCode\030\010 \001(\t\"" +
      "~\n\010DataType\022\010\n\004PING\020\000\022\n\n\006ONLINE\020\001\022\016\n\nONL" +
      "INE_ACK\020\002\022\013\n\007OFFLINE\020\003\022\017\n\013OFFLINE_ACK\020\004\022" +
      "\016\n\nKEY_STRIKE\020\005\022\014\n\010MSG_INFO\020\006\022\020\n\014MSG_INF" +
      "O_ACK\020\007B2\n\036com.letv.accountLogin.protobu",
      "fB\020ControlDataProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_letv_accountLogin_protobuf_Parcel_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_letv_accountLogin_protobuf_Parcel_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_letv_accountLogin_protobuf_Parcel_descriptor,
              new java.lang.String[] { "Type", "From", "To", "KeyCode", "MsgInfo", "Token", "Signature", "ErrorCode", },
              com.letv.accountLogin.protobuf.ControlDataProto.Parcel.class,
              com.letv.accountLogin.protobuf.ControlDataProto.Parcel.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
